[package]
name = "introvert"
version = "0.1.0"
edition = "2024"

[dependencies]
azalea = { git = "https://github.com/azalea-rs/azalea", version = "0.13.0" }
eyre = "0.6.12"
serde = "1.0.219"
serde_json = "1.0.142"
tokio = "1.47.1"
tracing = "0.1.41"
