name: Publish Docker Image

on:
   push:
      branches:
         - master
      tags:
         - "*"
   workflow_dispatch:

env:
   REGISTRY: ghcr.io
   IMAGE: nea89o/introvert

permissions:
    contents: read
    packages: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
        -   uses: docker/metadata-action@v5
            id: meta
            with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
                tags: |
                    type=ref,event=branch
                    type=semver,pattern={{version}}
                    type=semver,pattern={{major}}.{{minor}}
                    type=semver,pattern={{major}}
                    type=sha
        -   uses: docker/login-action@v3
            with:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
                registry: ${{ env.REGISTRY }}

        -   uses: docker/setup-buildx-action@v3
        -   uses: docker/build-push-action@v6
            with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
